export { default as LoginPage } from './LoginPage';
export { default as OverviewPage } from './OverviewPage';
export { default as MyArticlesPage } from './MyArticlesPage';
export { default as WaitingRoomPage } from './WaitingRoomPage';
export { default as ContactPanelPage } from './ContactPanelPage';
export { default as AdminPanelPage } from './AdminPanelPage';
export { default as NewArticlePage } from './NewArticlePage';
export { default as MyAccountPage } from './MyAccountPage';
export { default as HelpPage } from './HelpPage';
